image: gitpod/workspace-postgres:latest
tasks:
  - before: >
      rvm install 2.6.10 &&
      rvm use 2.6.10 &&
      cp config/database.gitpod.yml config/database.yml
    init: bin/setup
    command: bin/rails server

