image: gitpod/workspace-postgres:latest
tasks:
  - before: >
      rvm install 2.7.4 &&
      rvm use 2.7.4 &&
      cp config/database.docker.yml config/database.yml
    env:
      DATABASE_URL: "postgres://localhost"
      DATABASE_NAME: "cononrails"
    init: bin/setup
    command: bin/rails server

