require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.1
  AutoCorrect: true
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/*rake'
    - 'lib/reporting/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 100
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Rails/ActionControllerTestCase:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false
