language: ruby
rvm:
  - 2.0.0-p247
env:
  - DB=postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database con_on_rails_test' -U postgres
  - sqlite3 -batch db/attendees.sqlite3 < db/attendees.seed
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
