language: ruby
rvm:
  - 1.9.3
env:
  - DB=mysql
  - RAILS_ENV=test
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database con_on_rails_test'
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake --trace
