version: "3.7"
services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: con_on_rails_development
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: con_on_rails:latest
    build: .
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres@db:5432/
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  db:
