version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: cononrails_dev
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db