#sqlite: &sqlite
#  adapter: sqlite3
#  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:

#postgresql: &postgresql
#  adapter: postgresql
#  username: postgres
#  password:
#  database: con_on_rails_<%= Rails.env %>
#  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "mysql" %>

#development:
#  <<: *defaults

test:
  <<: *defaults
  database: con_on_rails_test

#production:
#  <<: *defaults
  # TODO: Add erb-echo of credentials
