mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: con_on_rails_<%= Rails.env %>

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: con_on_rails_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || 'mysql' %>

test:
  <<: *defaults

attendees:
  adapter: sqlite3
  database: "db/attendees.sqlite3"
  timeout: 500
