# Screw it. Right now, I only care about one database, and for some reason, the official tricks aren't working.

test:
  adapter: mysql2
  username: root
  password:
  pool: 5
  timeout: 5000
  host: localhost
  database: con_on_rails_test

attendees:
  adapter: sqlite3
  database: "db/attendees.sqlite3"
  timeout: 500
